#!/bin/bash

set -eux

SCRIPT_DIR=$(cd $(dirname $0); pwd)

RLY_HOME="$HOME/.yui-relayer"
RLY="${RLY_BIN} --debug"

echo "Generating ${RLY_BIN} configurations..."

# Ensure ${RLY_BIN} is installed
if ! [ -x ${RLY_BIN} ]; then
  echo "Error: ${RLY_BIN} is not installed." >&2
  exit 1
fi

rm -rf ${RLY_HOME} &> /dev/null

${RLY} config init
${RLY} chains add-dir configs/demo/
